#!/bin/bash

# source the ciop functions (e.g. ciop-log, ciop-getparam)
source ${ciop_job_include}

ciop-log "INFO" "hello!"

while read input
do 
  ciop-log "INFO" "hello! ${input}"
  ciop-browseresults -R ${input} |  tr -d '\r' | ciop-publish -s  
done
